
  CREATE TABLE "PMS_PROJECTS_TBL" 
   (	"PROJECT_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" NUMBER, 
	"BUDGET" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MENTOR_ID" NUMBER, 
	 PRIMARY KEY ("PROJECT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PMS_PROJECTS_TBL" ADD CONSTRAINT "PMS_PROJECTS_TBL_CON" FOREIGN KEY ("MENTOR_ID")
	  REFERENCES "PMS_MENTORS_TBL" ("MENTOR_ID") ENABLE;
