
  CREATE TABLE "PMS_TASK_TBL" 
   (	"TASK_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"TASK_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" NUMBER, 
	"PRIORITY" NUMBER, 
	 PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE
   ) ;
