
  CREATE TABLE "SMP_TASK_RESOURCES_TBL" 
   (	"TASK_ID" NUMBER, 
	"RESOURCE_ID" NUMBER, 
	"ALLOCATION_PERCENTAGE" NUMBER, 
	 CONSTRAINT "SMP_TASK_RESOURCES_TBL_CON_P_K" PRIMARY KEY ("TASK_ID", "RESOURCE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SMP_TASK_RESOURCES_TBL" ADD CONSTRAINT "SMP_TASK_RESOURCES_TBL_CON" FOREIGN KEY ("TASK_ID")
	  REFERENCES "SMP_TASK_TBL" ("TASK_ID") ENABLE;
  ALTER TABLE "SMP_TASK_RESOURCES_TBL" ADD CONSTRAINT "SMP_TASK_RESOURCES_TBL_CON_F" FOREIGN KEY ("RESOURCE_ID")
	  REFERENCES "SMP_RESOURCES_TBL" ("RESOURCE_ID") ENABLE;