
  CREATE TABLE "SMP_COMMENTS_TBL" 
   (	"COMMENT_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"COMMENT_TEXT" VARCHAR2(1000), 
	"COMMENT_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("COMMENT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SMP_COMMENTS_TBL" ADD CONSTRAINT "SMP_COMMENTS_TBL_CON" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "SMP_PROJECTS_TBL" ("PROJECT_ID") ENABLE;
  ALTER TABLE "SMP_COMMENTS_TBL" ADD CONSTRAINT "SMP_COMMENTS_TBL_CON_F" FOREIGN KEY ("TASK_ID")
	  REFERENCES "SMP_TASK_TBL" ("TASK_ID") ENABLE;
  ALTER TABLE "SMP_COMMENTS_TBL" ADD CONSTRAINT "SMP_COMMENTS_TBL_CON_F_K" FOREIGN KEY ("USER_ID")
	  REFERENCES "SMP_USERS_TBL" ("USER_ID") ENABLE;