
  CREATE TABLE "SMP_TIME_LOGS_TBL" 
   (	"LOG_ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"RESOURCE_ID" NUMBER, 
	"LOG_DATE" DATE, 
	"HOURS" NUMBER, 
	"DESCRIPTION" VARCHAR2(500), 
	 PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SMP_TIME_LOGS_TBL" ADD CONSTRAINT "SMP_TIME_LOGS_TBL_CON" FOREIGN KEY ("TASK_ID")
	  REFERENCES "SMP_TASK_TBL" ("TASK_ID") ENABLE;
  ALTER TABLE "SMP_TIME_LOGS_TBL" ADD CONSTRAINT "SMP_TIME_LOGS_TBL_CON_F" FOREIGN KEY ("RESOURCE_ID")
	  REFERENCES "SMP_RESOURCES_TBL" ("RESOURCE_ID") ENABLE;