
  CREATE TABLE "PMS_TASK_RESOURCES_TBL" 
   (	"TASK_ID" NUMBER PRIMARY KEY , 
	"RESOURCE_ID" NUMBER, 
	"ALLOCATION_PERCENTAGE" NUMBER, 
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PMS_TASK_RESOURCES_TBL" ADD CONSTRAINT "PMS_TASK_RESOURCES_TBL_CON" FOREIGN KEY ("TASK_ID")REFERENCES "PMS_TASK_TBL" ("TASK_ID") ENABLE;
  ALTER TABLE "PMS_TASK_RESOURCES_TBL" ADD CONSTRAINT "PMS_TASK_RESOURCES_TBL_CON_F" FOREIGN KEY ("RESOURCE_ID") REFERENCES "PMS_RESOURCES_TBL" ("RESOURCE_ID") ENABLE;
