
  CREATE TABLE "SMP_DOCUMENTS_TBL" 
   (	"DOCUMENT_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"DOCUMENT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"FILE_PATH" VARCHAR2(500), 
	"UPLOADED_BY" NUMBER, 
	"UPLOAD_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("DOCUMENT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SMP_DOCUMENTS_TBL" ADD CONSTRAINT "SMP_DOCUMENTS_TBL_CON" FOREIGN KEY ("UPLOADED_BY")
	  REFERENCES "SMP_USERS_TBL" ("USER_ID") ENABLE;
  ALTER TABLE "SMP_DOCUMENTS_TBL" ADD CONSTRAINT "SMP_DOCUMENTS_TBL_CON_F" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "SMP_PROJECTS_TBL" ("PROJECT_ID") ENABLE;