
  CREATE TABLE "SMP_MENTORS_TBL" 
   (	"MENTOR_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(100), 
	"LAST_NAME" VARCHAR2(100), 
	"PHONE_NUMBER" NUMBER, 
	"ADDRESS" VARCHAR2(500), 
	"GENDER_ID" NUMBER, 
	"BIRTH_DATE" DATE, 
	 PRIMARY KEY ("MENTOR_ID")
  USING INDEX  ENABLE
   ) ;