CREATE TABLE "PMS_TIME_LOGS_TBL" (
	"LOG_ID" NUMBER PRIMARY KEY, 
	"TASK_ID" NUMBER, 
	"RESOURCE_ID" NUMBER, 
	"LOG_DATE" DATE, 
	"HOURS" NUMBER, 
	"DESCRIPTION" VARCHAR2(500), 
  USING INDEX  ENABLE
);

  ALTER TABLE "PMS_TIME_LOGS_TBL" ADD CONSTRAINT "PMS_TIME_LOGS_TBL_CON" FOREIGN KEY ("TASK_ID") REFERENCES "PMS_TASK_TBL" ("TASK_ID") ENABLE;
  ALTER TABLE "PMS_TIME_LOGS_TBL" ADD CONSTRAINT "PMS_TIME_LOGS_TBL_CON_F" FOREIGN KEY ("RESOURCE_ID") REFERENCES "PMS_RESOURCES_TBL" ("RESOURCE_ID") ENABLE;
