
  CREATE TABLE "PMS_GENDER_TBL" 
   (	"GENDER_ID" NUMBER NOT NULL ENABLE, 
	"GENDER_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PMS_GENDER_TBL_CON" PRIMARY KEY ("GENDER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PMS_TRG_GENDER" 
before
insert or update or delete on "PMS_GENDER_TBL"
for each row
begin
    IF INSERTING THEN
        IF :NEW.GENDER_ID IS NULL THEN
            :NEW.GENDER_ID := PMS_SEQ_GENDER.NEXTVAL;
        END IF;
    END IF;
END;
/
ALTER TRIGGER "PMS_TRG_GENDER" ENABLE;