
  CREATE TABLE "PMS_TASK_TBL" 
   (	"TASK_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"DEVELOPER_ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"STATUS_ID" NUMBER, 
	"TASK_NAME" VARCHAR2(1000), 
	"DESCRIPTION" VARCHAR2(1000), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	 PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PMS_TASK_TBL" ADD CONSTRAINT "PMS_TASK_TBL_CON" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PMS_PROJECTS_TBL" ("PROJECT_ID") ENABLE;
  ALTER TABLE "PMS_TASK_TBL" ADD CONSTRAINT "PMS_TASK_TBL_CON_2" FOREIGN KEY ("DEVELOPER_ID")
	  REFERENCES "PMS_DEVELOPERS_TBL" ("DEVELOPER_ID") ENABLE;
  ALTER TABLE "PMS_TASK_TBL" ADD CONSTRAINT "PMS_TASK_TBL_CON_3" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "PMS_ROLES_TBL" ("ROLE_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PMS_TRG_TASK" 
before
insert or update or delete on "PMS_TASK_TBL"
for each row
begin
    IF INSERTING THEN
        IF :NEW.TASK_ID IS NULL THEN
            :NEW.TASK_ID := PMS_SEQ_TASK.NEXTVAL;
        END IF;
    END IF;
end;
/
ALTER TRIGGER "PMS_TRG_TASK" ENABLE;