
  CREATE TABLE "PMS_MENTORS_TBL" 
   (	"MENTOR_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(100), 
	"LAST_NAME" VARCHAR2(100), 
	"PHONE_NUMBER" NUMBER, 
	"ADDRESS" VARCHAR2(500), 
	"GENDER_ID" NUMBER, 
	"BIRTH_DATE" DATE, 
	 PRIMARY KEY ("MENTOR_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PMS_MENTORS_TBL" ADD CONSTRAINT "PMS_MENTORS_TBL_CON" FOREIGN KEY ("GENDER_ID")
	  REFERENCES "PMS_GENDER_TBL" ("GENDER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PMS_TRG_MENTORS" 
before
insert or update or delete on "PMS_MENTORS_TBL"
for each row
begin
    IF INSERTING THEN
        IF :NEW.MENTOR_ID IS NULL THEN
            :NEW.MENTOR_ID := PMS_SEQ_MENTORS.NEXTVAL;
        END IF;
    END IF;
END;
/
ALTER TRIGGER "PMS_TRG_MENTORS" ENABLE;