
  CREATE TABLE "PMS_DOCUMENTS_TBL" 
   (	"DOCUMENT_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"DOCUMENT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"FILE_PATH" VARCHAR2(1000), 
	"UPLOADED_BY" NUMBER, 
	"UPLOAD_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("DOCUMENT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PMS_DOCUMENTS_TBL" ADD CONSTRAINT "SMP_DOCUMENTS_TBL_CON" FOREIGN KEY ("UPLOADED_BY")
	  REFERENCES "PMS_DEVELOPERS_TBL" ("DEVELOPER_ID") ENABLE;
  ALTER TABLE "PMS_DOCUMENTS_TBL" ADD CONSTRAINT "SMP_DOCUMENTS_TBL_CON_F" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PMS_PROJECTS_TBL" ("PROJECT_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PMS_TRG_DOCUMENTS" 
before
insert or update or delete on "PMS_DOCUMENTS_TBL"
for each row
begin
    IF INSERTING THEN
        IF :NEW.DOCUMENT_ID IS NULL THEN
            :NEW.DOCUMENT_ID := PMS_SEQ_DOCUMENT.NEXTVAL;
        END IF;
    END IF;
END;
/
ALTER TRIGGER "PMS_TRG_DOCUMENTS" ENABLE;