
  CREATE TABLE "PMS_PROJECTS_TBL" 
   (	"PROJECT_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(500), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS_ID" NUMBER, 
	"BUDGET" NUMBER, 
	"TASKMASTER_ID" NUMBER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MENTOR_ID" NUMBER, 
	 PRIMARY KEY ("PROJECT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "PMS_PROJECTS_TBL" ADD CONSTRAINT "SMP_PROJECTS_TBL_CON" FOREIGN KEY ("MENTOR_ID")
	  REFERENCES "PMS_MENTORS_TBL" ("MENTOR_ID") ENABLE;
  ALTER TABLE "PMS_PROJECTS_TBL" ADD CONSTRAINT "PMS_PROJECTS_TBL_CON_FU" FOREIGN KEY ("TASKMASTER_ID")
	  REFERENCES "PMS_TASKMASTER_TBL" ("TASKMASTER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PMS_TRG_PROJECTS" 
before
insert or update or delete on "PMS_PROJECTS_TBL"
for each row
begin
    IF INSERTING THEN
        IF :NEW.PROJECT_ID IS NULL THEN
            :NEW.PROJECT_ID := PMS_SEQ_PROJECTS.NEXTVAL;
        END IF;
    END IF;
END;
/
ALTER TRIGGER "PMS_TRG_PROJECTS" ENABLE;